import { Theme, type ThemeColor } from "@earendil-works/pi-coding-agent";

export type TestThemeBackgroundColors = ConstructorParameters<typeof Theme>[1];

export const TEST_THEME_COLORS = {
    accent: "#8ab4f8",
    border: "#666666",
    borderAccent: "#8ab4f8",
    borderMuted: "#555555",
    success: "#64c987",
    error: "#f28b82",
    warning: "#fdd663",
    muted: "#888888",
    dim: "#777777",
    text: "#dddddd",
    thinkingText: "#bbbbbb",
    userMessageText: "#ffffff",
    customMessageText: "#dddddd",
    customMessageLabel: "#8ab4f8",
    toolTitle: "#dddddd",
    toolOutput: "#cccccc",
    toolDiffAdded: "#89d185",
    toolDiffRemoved: "#f48771",
    toolDiffContext: "#d4d4d4",
    mdHeading: "#8ab4f8",
    mdLink: "#8ab4f8",
    mdLinkUrl: "#82aaff",
    mdCode: "#a8c7a0",
    mdCodeBlock: "#cccccc",
    mdCodeBlockBorder: "#666666",
    mdQuote: "#bbbbbb",
    mdQuoteBorder: "#666666",
    mdHr: "#666666",
    mdListBullet: "#8ab4f8",
    syntaxComment: "#7f8c8d",
    syntaxKeyword: "#c4a7e7",
    syntaxFunction: "#8ab4f8",
    syntaxVariable: "#dddddd",
    syntaxString: "#a8c7a0",
    syntaxNumber: "#f6c177",
    syntaxType: "#9ccfd8",
    syntaxOperator: "#bbbbbb",
    syntaxPunctuation: "#bbbbbb",
    thinkingOff: "#777777",
    thinkingMinimal: "#777777",
    thinkingLow: "#8ab4f8",
    thinkingMedium: "#c4a7e7",
    thinkingHigh: "#f6c177",
    thinkingXhigh: "#f28b82",
    thinkingMax: "#f28b82",
    bashMode: "#64c987",
} satisfies Record<ThemeColor, string>;

export const TEST_THEME_BACKGROUND_COLORS = {
    selectedBg: "#333333",
    userMessageBg: "#1E1E2E",
    customMessageBg: "#242436",
    toolPendingBg: "#222222",
    toolSuccessBg: "#123012",
    toolErrorBg: "#301212",
} satisfies TestThemeBackgroundColors;
