// Generated by pi-extension-settings. Do not edit.
const artifact = {
    "formatVersion": 1,
    "fingerprint": "json-sha256-v1:601e66f50568da72a5b0c6ec01aed374b0aba562a94cbf53328b81594e798ee1",
    "semanticFingerprint": "typebox-value-hash-v1:c2c2ac91b2c9a528",
    "defaultSettings": {
        "preserveTools": [],
        "mutations": {
            "defaultView": "full",
            "previewLines": 6,
            "limits": {
                "maxDiffBytes": 524288,
                "maxDiffLines": 5000,
                "maxWritePreviewBytes": 65536,
                "maxDeletePreimageBytes": 262144
            }
        },
        "appearance": {
            "diffBackgroundStyle": "two-tone",
            "diffLineNumberStyle": "dual",
            "narrowDiffLayout": "paired",
            "sideBySideLayout": "content-aware",
            "addedRowBackground": "#213A2B",
            "deletedRowBackground": "#4A221D",
            "addedContentBackground": "#0D5728",
            "deletedContentBackground": "#762925",
            "instructionPathColor": null,
            "dimUnchangedDiffText": false
        },
        "debugLog": {
            "enabled": false,
            "path": "debug.log",
            "maxBytes": null,
            "memorySampleIntervalMs": 10000
        },
        "renderCache": {
            "maxBytes": 67108864,
            "maxEntries": 10000
        },
        "toolCallIndicator": {
            "symbol": "•",
            "bold": true
        },
        "toolLabels": {
            "mode": "static"
        },
        "writePreview": {
            "movingViewport": true
        },
        "syntax": {
            "preloadLanguages": [
                "markdown",
                "bash",
                "python",
                "typescript",
                "javascript",
                "json"
            ],
            "bracketPairColoring": true,
            "projectLanguageDetection": {
                "enabled": true
            }
        },
        "patches": {
            "assistantSeparator": true,
            "workingWidgetSpacing": false,
            "autocompleteCleanup": true,
            "markdownSyntax": true,
            "thirdPartyToolRenderers": true
        },
        "scriptPreview": {
            "headerLayout": "auto",
            "maxCodePreviewLines": 8,
            "showPrologueOmission": false,
            "shellLayout": "auto",
            "shellOperatorPosition": "trailing",
            "formatters": {}
        }
    }
} as const;

export default artifact;
